# Generated by Django 5.0.1 on 2024-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lo',
            name='password',
        ),
    ]
