# Generated by Django 5.0.1 on 2024-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='code',
        ),
    ]
