# Generated by Django 5.0.1 on 2024-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_password_registration_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=300)),
                ('hospital_image', models.ImageField(upload_to='hospitalimages')),
                ('hospital_address', models.TextField()),
                ('hospital_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=300)),
                ('patient_age', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('mobile_number', models.PositiveBigIntegerField()),
                ('Emargency_number', models.TextField(null=True)),
                ('current_medication', models.TextField()),
                ('allergies', models.TextField()),
                ('past_surgeries', models.TextField()),
                ('insurance_policy', models.TextField()),
                ('Policy_number', models.TextField()),
                ('special_request', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200),
        ),
    ]
