# Generated by Django 5.0.1 on 2024-02-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hospital_patient_info_alter_registration_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hospital',
            new_name='info',
        ),
    ]
