# Generated by Django 5.0.1 on 2024-02-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_hospital_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='hospital_image',
        ),
    ]
