# Generated by Django 5.0.1 on 2024-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_info_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='hospital_image',
            field=models.ImageField(default=111, upload_to='hospitalimages'),
            preserve_default=False,
        ),
    ]
