# Generated by Django 5.0.1 on 2024-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hospital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hospital',
            new_name='hospitalname',
        ),
    ]
