# Generated by Django 5.0.1 on 2024-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_info_hospital_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(max_length=300)),
                ('Bed_id', models.CharField(max_length=300, unique=True)),
                ('Ward_number', models.IntegerField()),
                ('Room_number', models.IntegerField()),
                ('Disease', models.CharField(max_length=200)),
                ('Bed_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Bed_id',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Bed_type',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Disease',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Hospital_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Room_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_info',
            name='Ward_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
