# Generated by Django 5.0.1 on 2024-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_lo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=500),
        ),
    ]
